# Generated by Django 3.2.6 on 2022-02-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormdet', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pass_date',
            field=models.DateTimeField(),
        ),
    ]
